name: "Ciconia - A New Markdown Parser for #PHP by Kazuyuki Hayashi"
description: "A New Markdown Parser for #PHP"
url: http://ciconia.kzykhys.com
paginate: 5
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
exclude: ['CNAME', 'vendor', 'composer.json', '_sami']